const { authenticateToken } = require("../middleware/auth");
const express = require("express");
const router = express.Router();
const CompanyRouter = require("./companyName.routes");
const StaffRouter = require("./staff.routes");
const AccountMasterRouter = require("./accountMaster.routes");
const AssignTaskRouter = require("./assignTask.routes");
const Order = require("./order.routes");
const Lead = require("./lead.routes");
const Purchase = require("./purchase.routes");
const QpPurchase = require("./QualityPurchase.routes");
const productItem = require("./productItem.routes");
const Inventory = require("./inventory.routes");
const fileUpload = require("./filesUpload.routes");
const status = require("./status.routes");
const Roles = require("./role.routes");
const filedownloadRouter = require("./fileDownload.routes");
const MaterialRouter = require("./material.routes");
const RoleDepartmentRouter = require("./roleDepartment.routes");
const RoleDepartmentCompanyRouter = require("./roleDepartmentCompany.routes");
const performanceInvoiceRoutes = require("./performanceInvoice.route");
const Vendor = require("./vendor.routes");
const BinderTypeRoutes = require("./binderType.routes");
const QpOrderRoutes = require("./qpOrder.routes");
const packagingOptions = require("./packagingOption.routes");
const paperGSM = require("./paperGSM.routes");
const marketData = require("./marketData.routes");
const kantan = require("./kantan.routes");
const complain = require("./complain.routes");
const report = require("./report.routes");
const factoryArrival = require("./factoryReturn.routes");


router.use("/staff", StaffRouter);
router.use(authenticateToken);
router.use("/company", CompanyRouter);
router.use("/report", report);
router.use("/account-master", AccountMasterRouter);
router.use("/assign-task", AssignTaskRouter);
router.use("/orders", Order);
router.use("/lead", Lead);
router.use("/binderType", BinderTypeRoutes);
router.use("/purchase", Purchase);
router.use("/qppurchase", QpPurchase);
router.use("/inventory", Inventory);
router.use("/vendor", Vendor);
router.use("/productItem", productItem);
router.use("/fileUpload", fileUpload);
router.use("/status", status);
router.use("/role", Roles);
router.use("/qporder", QpOrderRoutes);
router.use("/packagingOptions", packagingOptions);
router.use("/paperGSM", paperGSM);
router.use("/market", marketData);
router.use("/kantan", kantan);
router.use("/filedownload", filedownloadRouter);
router.use("/material", MaterialRouter);
router.use("/roleDepartment", RoleDepartmentRouter);
router.use("/roleDepartmentCompany", RoleDepartmentCompanyRouter);
router.use("/performance-invoice", performanceInvoiceRoutes);
router.use("/complain", complain);
router.use("/factoryReturn", factoryArrival);
module.exports = router;
